version: '3.8'

services:
  sankarea:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sankarea-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/healthcheck"]
      interval: 1m
      timeout: 10s
      retries: 3
