version: '3.8'
services:
  sankarea:
    build: .
    container_name: sankarea
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
    ports:
      - "8080:8080" # Health API port
