- name: Reuters
  url: https://www.reuters.com/rssFeed
  bias: center
- name: Fox News
  url: https://www.foxnews.com/about/rss
  bias: right
- name: CNN
  url: https://www.cnn.com/rss
  bias: left
- name: CDC
  url: https://tools.cdc.gov/api/v2/resources/media/404952.rss
  bias: gov
