# Left-Leaning / Center-Left
- name: "NPR"
  url: "https://www.npr.org/rss/rss.php?id=1001"
  bias: "left"

# Center / Mainstream
- name: "USA Today"
  url: "http://rssfeeds.usatoday.com/usatoday-NewsTopStories"
  bias: "center"

# US Government
- name: "NASA Breaking News"
  url: "https://www.nasa.gov/rss/dyn/breaking_news.rss"
  bias: "gov"
