version: 1.0.0
keywords:
  - impeachment
  - filibuster
  - Supreme Court
feed_types:
  political_news:
    ttl_days: 1
    similarity_threshold: 90.0
colors:
  default: 15844367
  government: 3447003
rss:
  - name: CDC News Releases
    url: https://tools.cdc.gov/api/v2/resources/media/404952.rss
    tags: [government]
  - name: CNN Politics
    url: https://rss.cnn.com/rss/cnn_allpolitics.rss
    tags: [mainstream]
  - name: Fox News Politics
    url: https://moxie.foxnews.com/google-publisher/politics.xml
    tags: [right]
html:
  - name: USA.gov
    url: https://www.usa.gov
    selector: "article"
    tags: [government]
categories: {}
