- name: "CNN"
  url: "http://rss.cnn.com/rss/cnn_topstories.rss"
  category: "Mainstream"
  bias: "Left-Center"
  factCheckAuto: true
  summarizeAuto: true
  active: true

- name: "Fox News"
  url: "http://feeds.foxnews.com/foxnews/latest"
  category: "Mainstream"
  bias: "Right"
  factCheckAuto: true
  summarizeAuto: true
  active: true

- name: "Reuters"
  url: "http://feeds.reuters.com/reuters/topNews"
  category: "International"
  bias: "Center"
  factCheckAuto: true
  summarizeAuto: true
  active: true

- name: "AP News"
  url: "https://rsshub.app/apnews/topics/apf-topnews"
  category: "International"
  bias: "Center"
  factCheckAuto: true
  summarizeAuto: true
  active: true

- name: "BBC"
  url: "http://feeds.bbci.co.uk/news/world/rss.xml"
  category: "International"
  bias: "Center-Left"
  factCheckAuto: true
  summarizeAuto: true
  active: true
