name: Export all secrets and vars as .env

on:
  workflow_dispatch: # lets you run this workflow manually in GitHub UI

jobs:
  export-env:
    runs-on: ubuntu-latest
    steps:
      - name: Output secrets and vars as .env lines
        run: |
          echo "# --- GitHub Secrets ---"
          echo "$ALLMYSECRETS" | jq -r 'to_entries[] | "\(.key)=\(.value)"'
          echo "# --- GitHub Vars ---"
          echo "$ALLMYVARS" | jq -r 'to_entries[] | "\(.key)=\(.value)"'
        shell: bash
        env:
          ALLMYSECRETS: ${{ toJSON(secrets) }}
          ALLMYVARS: ${{ toJSON(vars) }}

